# Generated by Django 4.2.2 on 2023-06-08 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('product_categotyId', models.IntegerField(primary_key=True, serialize=False)),
                ('product_categotyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productData', models.DateField()),
                ('product_categotyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
