# Generated by Django 4.2.2 on 2023-06-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productData',
            new_name='productDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productDescription',
        ),
        migrations.AlterField(
            model_name='product',
            name='productId',
            field=models.PositiveIntegerField(),
        ),
    ]
